title: National Archives of Singapore
title-abbreviated: NAS
description: >- # this means to ignore newlines until "baseurl:"
  Official website of the XXI International Oral History Association Conference 2020 held in Singapore, 22-26 Jun 2020
url: "https://www.ioha2020.sg/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: false

# Feedback Form URL
feedback_form_url: "https://form.gov.sg/5ccff2c0f4552800107651c2"

# FAQ URL

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

collections:
  who-we-are:
    output: true
  programme:
    output: true
  registration:
    output: true
resources_name: conference

is_government: false
